# Generated by Django 4.2.4 on 2023-08-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_systemstatus_last_unsuccessful_execution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemStatus',
        ),
    ]
